apiVersion: v1
kind: Service
metadata:
  labels:
    app: metricsproxy
  name: metricsproxy
spec:
  ports:
  - name: metrics
    port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    app: metricsproxy
  type: ClusterIP
