apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metricsproxy
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scrapeTimeout: 30s
  selector:
    matchLabels:
      app: metricsproxy
